version: '3.8'
services:
  app:
    build:
      context: .
      # MODE=[dev | prod] docker compose up -d --build 
      target: $MODE
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
