# Use the official etcd image from Docker Hub
FROM quay.io/coreos/etcd:v3.5.6

# Set environment variables for etcd configuration
ENV ETCD_DATA_DIR /etcd-data
ENV ETCD_LISTEN_PEER_URLS http://0.0.0.0:2380
ENV ETCD_LISTEN_CLIENT_URLS http://0.0.0.0:2379
ENV ETCD_ADVERTISE_CLIENT_URLS http://localhost:2379
ENV ETCD_INITIAL_ADVERTISE_PEER_URLS http://localhost:2380
ENV ETCD_INITIAL_CLUSTER "default=http://localhost:2380"
ENV ETCD_INITIAL_CLUSTER_TOKEN "etcd-cluster-1"
ENV ETCD_INITIAL_CLUSTER_STATE "new"
ENV ETCD_HEARTBEAT_INTERVAL 100
ENV ETCD_ELECTION_TIMEOUT 1000

# Expose the ports
EXPOSE 2379 2380

# Command to run etcd
CMD ["/usr/local/bin/etcd"]