name: Docker Compose Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker Compose environment (optional)
      - name: Set up Docker Compose environment
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      # Step 4: Build and bring up Docker Compose services
      - name: Build and run Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build MODE=prod

      # Step 5: Verify services are up and running
      - name: Check running services
        run: docker-compose ps

      # Step 6: Tear down services (clean up)
      - name: Stop and remove Docker Compose services
        if: always() # This ensures that it runs even if previous steps fail
        run: docker-compose down
